#
apiVersion: v1
kind: Service
metadata:
  name: fare-deduction
  labels:
    app: fare-deduction
spec:
  selector:
    app: fare-deduction
  ports:
    - protocol: "TCP"
      port: 6100
      targetPort: 6100