apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: rfid-card
spec:
  selector:
    matchLabels:
      app: rfid-card
  replicas: 1 #change is as per requirement
  template:
    metadata:
      labels:
        app: rfid-card
    spec:
      containers:
        - name: rfid-card
          image: rajendransurya/rfid-card:latest
          ports:
            - containerPort: 6300
          env:
            - name: PG_HOSTNAME
              value: "34.170.205.253"
            - name: PG_DBNAME
              value: "integrated_transport_system"
            - name: PG_USERNAME
              value: "postgres"
            - name: PG_PWD
              value: "admin"
            - name: PG_PORT
              value: "5432"